#define ABS_SRCDIR "/Users/matthewphilips/src/ruby-3.2.2"
#define BUILDDIR   "/Users/matthewphilips/src/ruby-3.2.2"
#define LIBPATHENV "DYLD_FALLBACK_LIBRARY_PATH"
#define PRELOADENV "DYLD_INSERT_LIBRARIES"
#define PATH_SEPARATOR ":"
#define PATH_SEP   ':'
#define EXTOUT     ".ext"
#define ARCH       "x86_64-darwin21"
#define SOEXT      "dylib"
